### ISSUE TITLE
Cannot view items

### ISSUE THREAD

**Issue by Jammingway** [giulianoriccio/Lua#25]
When attempting to select items from an NPC that would normally display the item Enternity steps in and skips it thinking it's more pauses. An example would be when purchasing Emp gear from a Curor/Dominion NPC. It's fine if it's an item you know what it is called, but is annoying when you are trying to inspect different items. Just a small issue, but one that's a little annoying.

**Comment by giulianoriccio** [comment]
Fixed.

**Comment by Jammingway** [comment]
Issue still occurs with viewing chest items in Abyssea, but it is certainly better in most other cases.

**Comment by giulianoriccio** [comment]
As a temp fix I excluded lines containing item names from enternity (the green ones) but then I noticed that they are not always written in the chat log when showing an item and, viceversa, even if they appear an item dialog is not always displayed, like Kilusha's items in Nashmau or chests for example.

I guess the only alternative is to add some NPCs as exceptions so that enternity will ignore them.
Please provide any NPC name that you think could be added to the exceptions.

**Comment by giulianoriccio** [comment]
Hello,
I'm sorry but I'm not playing FFXI anymore and this project fork is not maintained since a few years ago.

If you are still experiencing the issue reported here, please resubmit it on the official [Windower/Lua repository](https://github.com/Windower/Lua).

Thank you for using my addons.
